name: Github Action example workflow
on: push
jobs:
  command:
    name: Exec command
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: NodeJS command
        uses: hiberbee/template-github-action-nodejs@main
        with:
          command: npm
          arguments: run release
